CREATE TABLE STUDENTS (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	date_of_birth DATE NOT NULL,
	email VARCHAR(128) NOT NULL,
	index_number INT NOT NULL,
	is_on_budget BOOLEAN NOT NULL,
	PRIMARY KEY (id)
);